[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/bienvenida-2025"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_OTZkZTExMmMtMzAzNi00NTVlLTlhMWQtMTY5YWVkMTA0Njgz%40thread.v2/0?context=%7b%22Tid%22%3a%229577482f-f879-4df0-9bb1-7e0fc583dba9%22%2c%22Oid%22%3a%22ccd95571-21be-4eb5-9cff-754b6ead474d%22%7d"
  status = 200
  force = true
