[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/sesion-de-bienvenida"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZTUyZjc1YWQtZjZhMS00MWY4LWIwZGItMjg0ZmJjY2IxYmE3%40thread.v2/0?context=%7b%22Tid%22%3a%229577482f-f879-4df0-9bb1-7e0fc583dba9%22%2c%22Oid%22%3a%22ccd95571-21be-4eb5-9cff-754b6ead474d%22%7d"
  force = true

[[redirects]]
  from = "/clases-semanales-1"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_MGUyYTY3ODMtMmE5NS00ZTBkLTg3YjktZjFhNjU3ZDVkZTRl%40thread.v2/0?context=%7b%22Tid%22%3a%229577482f-f879-4df0-9bb1-7e0fc583dba9%22%2c%22Oid%22%3a%22ccd95571-21be-4eb5-9cff-754b6ead474d%22%7d"
  force = true

[[redirects]]
  from = "/clases-semanales-2"
  to = "https://teams.microsoft.com/l/meetup-join/19%3ameeting_MDUxNDgzODYtZjk3Ni00N2I0LWE2ZjAtYTEzOGIxMTUzN2Ew%40thread.v2/0?context=%7b%22Tid%22%3a%229577482f-f879-4df0-9bb1-7e0fc583dba9%22%2c%22Oid%22%3a%22ccd95571-21be-4eb5-9cff-754b6ead474d%22%7d"
  force = true
